### ISSUE TITLE
[TODO] 任意の範囲の乱数

### ISSUE THREAD

**Issue by Katudonsan** [TUSBAD/TUSBAD_Prototype#13]
### 重要度

通常

### このTODOはこのTUSBAD Versionに影響が出る

Prototype

## 何故必要なのか?
1.乱数は様々な場面で使用されるため

## 何故必要なのか
1.一回一回乱数を算出する必要があり、煩雑。

## 何故この重要度なのか
1.もうすでに完成したため

## いつまで対応が必要か
1.完成済みのため緊急性なし。

**Comment by Syareene** [comment]
パット見いい感じだけど、実行者は必ずしもプレイヤーとは限らないので、基本的にはダミープレイヤーに結果とかを代入し値を返すほうが好ましいかも。

**Comment by Katudonsan** [comment]
はい。
…ダミープレイヤーとしてrandmanというのを生成しようとしたのですが
おそらく@sを変更する場所を誤り、「４」しか返ってこなくなったので
いったんそのまま提出いたしました

**Comment by Syareene** [comment]
あ、おけおけ。
そのへんはまあまあおいおいって感じで

**Comment by Katudonsan** [comment]
[Random_Pack.zip](https://github.com/user-attachments/files/16484581/Random_Pack.zip)
第二版です
確率プレディケイト＋架空プレイヤーでの乱数抽選を行いました

**Comment by Katudonsan** [comment]
いったんテストしてみたので自分のブランチでプッシュしました

**Comment by Katudonsan** [comment]
マージされたので完了。Issueクローズします。
